### ISSUE TITLE
Please Fix Andy

### ISSUE THREAD

**Issue by jake32321** [siucacm/siucacm.github.io#2]
Andy's pic is messed up and I'm guessing it's due to the size.  If someone has time to fix this please do.

**Comment by ethanx94** [comment]
Righto, he was too tall. You can't blame him, just born with good genetics.

**Comment by Twistedchurro** [comment]
lol

On Sat, Aug 13, 2016 at 11:07 PM, Ethan Richardson <notifications@github.com
