### ISSUE TITLE
Ayush oval?

### ISSUE THREAD

**Issue by akohli96** [siucacm/siucacm.github.io#5]
Dawgs, anyone know how to make my image on website a normal circle like everyone else?

**Comment by ethanx94** [comment]
Took care of it. It had to be a square ratio picture. So I cropped it around.

**Comment by akohli96** [comment]
Check again

**Comment by ethanx94** [comment]
Looks good on my end. Try emptying your cache maybe?
<img width="1680" alt="screen shot 2016-10-25 at 1 01 14 am" src="https://cloud.githubusercontent.com/assets/4449468/19674552/992300b8-9a4e-11e6-8cf7-639572351e04.png">

**Comment by akohli96** [comment]
It good.
